# Generated by Django 6.0.3 on 2026-04-09 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_enrollment_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.club', verbose_name='Гурток'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='date_joined',
            field=models.DateField(auto_now_add=True, verbose_name='Дата приєднання'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.student', verbose_name='Учень'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(verbose_name='Вік'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(max_length=10, verbose_name='Номер класу'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Прізвище'),
        ),
    ]
