# Generated by Django 6.0.3 on 2026-04-09 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_club_description_alter_club_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Реєстрація', 'verbose_name_plural': 'Реєстрації'},
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(3, message='Вік не може бути меншим за 3 років.'), django.core.validators.MaxValueValidator(129, message='Вік не може перевищувати 129 років.')], verbose_name='Вік'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Поле повинно містити лише літери.', regex="^[A-Za-zА-Яа-яіІїЇєЄґҐ\\'\\-]+$")], verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Поле повинно містити лише літери.', regex="^[A-Za-zА-Яа-яіІїЇєЄґҐ\\'\\-]+$")], verbose_name='Прізвище'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'club')},
        ),
    ]
