# Generated by Django 6.0.3 on 2026-04-10 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_enrollment_options_alter_student_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='ІПН повинен містити рівно 10 цифр.', regex='^\\d{10}$')], verbose_name='ІПН'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(max_length=5, verbose_name='Номер класу'),
        ),
    ]
