# Generated by Django 6.0.3 on 2026-04-10 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_student_student_id_alter_student_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='ІПН повинен містити рівно 10 цифр.', regex='^\\d{10}$')], verbose_name='ІПН'),
        ),
    ]
